# filepath: /home/acadenice/kevin/docker-compose.yml

services:
  database-kevin:
    image: postgres:latest
    hostname: database_kevin
    container_name: database-kevin
    networks:
      - kevin
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${CO_DB_NAME}

  frontend-kevin:
    build:
      context: ./frontend-kevin
      dockerfile: Dockerfile
    container_name: frontend-kevin
    environment:
      - API_URL=${API_URL}
      - DEV=${R_DEV}
      - CREATE_NEW_PROJECT=${R_CREATE_NEW_PROJECT}
    hostname: frontend-kevin
    restart: always
    volumes:
      - ./frontend-kevin/app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=admin_proxy"
      - "traefik.http.routers.frontend-kevin-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-kevin-secure.rule=Host(`${PRENOM}-app.${DOMAIN_NAME}`)"
      - "traefik.http.routers.frontend-kevin-secure.service=frontend-kevin"
      - "traefik.http.services.frontend-kevin.loadbalancer.server.port=3000"
    networks:
      - kevin

  webdb:
    image: webdb/app
    container_name: webdb
    depends_on:
      - database-kevin
    networks:
      - kevin
    volumes:
      - "$HOME/.ssh:/root/.ssh:ro"
      - "$HOME/.webdb:/usr/src/app/static/version"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=admin_proxy"
      - "traefik.http.routers.webdb-kevin-secure.entrypoints=websecure"
      - "traefik.http.routers.webdb-kevin-secure.rule=Host(`${PRENOM}-db.${DOMAIN_NAME}`)"
      - "traefik.http.routers.webdb-kevin-secure.service=webdb-kevin"
      - "traefik.http.services.webdb-kevin.loadbalancer.server.port=22071"

  api-kevin:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: api-kevin
    depends_on:
      - database-kevin
    hostname: api-kevin
    restart: always
    volumes:
      - ./core/api:/api
    environment:
      - CREATE_NEW_PROJECT=${CO_CREATE_NEW_PROJECT}
      - PROJECT_NAME=${CO_PROJECT_NAME}
      - DB_DEV=${CO_DB_DEV}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${CO_DB_NAME}
      - DB_HOST=database_kevin
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - APP_NAME="Core Centralis"
      - APP_URL="http://${PRENOM}-api.${DOMAIN_NAME}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=admin_proxy"
      - "traefik.http.routers.api-kevin-secure.entrypoints=websecure"
      - "traefik.http.routers.api-kevin-secure.rule=Host(`${PRENOM}-api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api-kevin-secure.service=api-kevin"
      - "traefik.http.services.api-kevin.loadbalancer.server.port=8000"
    networks:
      - kevin

networks:
  kevin:
